const fromOptions = [
    { label: "POL", value: "BND" },
    { label: "JABEL ALI", value: "JEA" },
    { label: "BND", value: "BND" },
    { label: "IRAN", value: "IRAN" },
    { label: "KANDLA", value: "KANDLA" },
    { label: "BUSHEHR", value: "BUSHEHR" },
    { label: "NHAVA SHEVA", value: "NHAVA SHEVA" },
    { label: "MUNDRA", value: "MUNDRA", },
    { label: "MOMBASA", value: "MOMBASA", },
    { label: "BANDAR IMAM KHOMEINI", value: "BANDAR IMAM KHOMEINI" },
    { label: "BUSHEHR", value: "BUSHEHR", },
    { label: "KHORRAM SHAHR", value: "KHORRAM SHAHR", },
    { label: "Assalouyeh", value: "Assalouyeh" },
    { label: "ABU DHABI", value: "ABU DHABI" },
    { label: "DAR ES SALAM", value: "DAR ES SALAM" },
    { label: "TANGER MED", value: "TANGER MED" },
    { label: "CASABLANCA", value: "CASABLANCA" },
    { label: "HAMAD", value: "HAMAD" },
    { label: "COLOMBO", value: "COLOMBO" },
    { label: "COCHIN", value: "COCHIN" },
    { label: "CHENNAI", value: "CHENNAI" },
    { label: "PORT KLANG", value: "PORT KLANG" },
    { label: "SINGAPORE", value: "SINGAPORE" },
    { label: "SHANGHAI", value: "SHANGHAI" },
    { label: "SHEKOU", value: "SHEKOU" },
    { label: "HAZIRA", value: "HAZIRA" },
    { label: "PIPAVA", value: "PIPAVA" }
]



const toOptions = [
    { label: "POD", value: "BND" },
    { label: "JABEL ALI", value: "JEA" },
    { label: "IRAN", value: "IRAN" },
    { label: "KANDLA", value: "KANDLA" },
    { label: "BUSHEHR", value: "BUSHEHR" },
    { label: "NHAVA SHEVA", value: "NHAVA SHEVA" },
    { label: "MUNDRA", value: "MUNDRA" },
    { label: "MOMBASA", value: "MOMBASA" },
    { label: " BANDAR IMAM KHOMEINI", value: "BANDAR IMAM KHOMEINI" },
    { label: "BUSHEHR", value: "BUSHEHR" },
    { label: "KHORRAM SHAHR", value: "KHORRAM SHAHR" },
    { label: "Assalouyeh", value: "Assalouyeh" },
    { label: "ABU DHABI", value: "ABU DHABI" },
    { label: "DAR ES SALAM ", value: "DAR ES SALAM" },
    { label: " TANGER MED ", value: "TANGER MED" },
    { label: "CASABLANCA", value: "CASABLANCA" },
    { label: "HAMAD", value: "HAMAD" },
    { label: "COLOMBO", value: "COLOMBO" },
    { label: "COCHIN", value: "COCHIN" },
    { label: "CHENNAI", value: "CHENNAI" },
    { label: "PORT KLANG", value: "PORT KLANG" },
    { label: "SINGAPORE", value: "SINGAPORE" },
    { label: "SHANGHAI", value: "SHANGHAI" },
    { label: "SHEKOU", value: "SHEKOU" },
    { label: "HAZIRA", value: "HAZIRA" },
    { label: "PIPAVA", value: "PIPAVA" },
]